[workspace]
members = [
    "web-codegen",
    "web-common"
]
resolver = "2"

[package]
name = "learn-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
web-codegen = { path = "web-codegen" }
web-common = { path = "web-common" }

tokio = { workspace = true }

# web框架
rocket = { workspace = true }
rocket_ws = { workspace = true }

# 数据库
redis = { workspace = true }
deadpool-redis = { workspace = true }
redis-macros = { workspace = true }

rbs = { workspace = true }
rbatis = { workspace = true }
rbdc-pg = { workspace = true }

# 序列化
serde = { workspace = true }
serde_json = { workspace = true }

# 懒加载
once_cell = { workspace = true }

# 登录认证
jsonwebtoken = { workspace = true }
rocket-jwt = { workspace = true }

# 文档
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

derive-new = { workspace = true }

anyhow = { workspace = true }


[workspace.dependencies]
# 异步模型
tokio = "1.37"

# web框架
rocket = { version = "0.5", features = ["json", "uuid", "secrets"] }
rocket_ws = "0.1"

# 数据库
redis = { version = "0.25", features = ["tokio-comp"] }
deadpool-redis = { version = "0.15", features = ["serde"] }
redis-macros = "0.3"

rbs = "4"
rbatis = "4"
rbdc-pg = "4"

# 序列化
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# 懒加载
once_cell = "1"

# 登录认证
jsonwebtoken = "9"
rocket-jwt = "0.5"

# 文档
utoipa = { version = "4", features = ["rocket_extras"] }
utoipa-swagger-ui = { version = "7", features = ["rocket"] }

md5 = "0.7"

derive-new = "0.6"

anyhow = "1"
