workspace = { members = ["sql-macro"] }
[package]
name = "learn-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5", features = ["json"] }
rocket_ws = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

once_cell = "1"

jsonwebtoken = "9"
rocket-jwt = "0.5"

rbs = "4"
rbatis = "4"
rbdc-pg = "4"

utoipa = { version = "4", features = ["rocket_extras"] }
utoipa-swagger-ui = { version = "6", features = ["rocket"] }

auth-macro = { path = "auth-macro" }
sql-macro = { path = "sql-macro" }
