services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 135246
    volumes:
      - /var/lib/docker/volumes/le_rocket/sql:/var/lib/postgresql/data
      - ./script/init_user_table.sql:/docker-entrypoint-initdb.d/init_user_table.sql
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
