version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 135246
      POSTGRES_DB: le_rocket
    volumes:
      - /var/lib/docker/volumes/le_rocket/sql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

