#[global]
#port = 8080

[default]
port = 8000
secret_key = "secret"

#[debug]

[debug.database.redis]
url = "redis://localhost/"

[debug.database.postgres]
url = "postgres://postgres:135246@localhost:5432/le_rocket"


#[release]