[package]
name = "im-codegen"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 代码生成工具
syn = { workspace = true }
quote = { workspace = true }

[lib]
proc-macro = true
