[package]
name = "im-codegen"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2", features = ["full", "visit-mut", "visit"] }
quote = "1"

[lib]
proc-macro = true
