name: Salvo CI with Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Test with Docker
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      # --wait 标志会使用 docker-compose.yml 中的 healthcheck
      # 它会等待所有服务都健康后，再继续下一步
      - name: 启动依赖服务
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          up-flags: '-d --wait'

      - name: 设置 Rust 环境
        uses: dtolnay/rust-toolchain@stable

      - name: 缓存依赖
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo.git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      # 关键：在这里设置 DATABASE_URL 环境变量，让测试代码能连接到数据库
      - name: 运行测试
        run: cargo test -p web-server --verbose
#        env:
#          # 这个 URL 必须与 docker-compose.yml 中的配置相匹配
#          # 主机是 localhost，因为我们已经将端口映射到了 Runner
#          DATABASE_URL: "postgres://user:password@localhost:5432/mydatabase_test"
#          # 如果你的应用需要，可以设置其他环境变量
#          RUST_LOG: "info"

      # 无论测试成功与否，这个步骤都会运行，以确保关闭 Docker 容器
      - name: 清理服务（可选但推荐）
        if: always()
        run: docker-compose down
